# add the GraphQL controller to the Neos backend request patterns

Wwwision:
  GraphQL:
    endpoints:
      neos/graphql:
        querySchema: Wwwision\Neos\GraphQL\Types\RootTypes\Query
        mutationSchema: Wwwision\Neos\GraphQL\Types\RootTypes\Mutation
Neos:
  Flow:
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Wwwision.Neos.GraphQL:controllerObjectName':
                pattern: ControllerObjectName
                patternOptions:
                  controllerObjectNamePattern: 'Wwwision\GraphQL\.*'
    mvc:
      routes:
        Wwwision.GraphQL:
          variables:
            endpoint: neos/graphql
